version: '3.7'
 services:
     web:
         build: .
         ports:
         - "8501:8501"
         volumes:
         - .:/code 
         
 version: '3.7'

 volumes:
     prometheus_data: {}
     grafana_data: {}

 services:
   prometheus:
     image: prom/prometheus:v2.1.0
     volumes:
       - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
     command:
       - '--config.file=/etc/prometheus/prometheus.yaml'
     ports:
       - '8080:8080'
